### ISSUE TITLE
Secret in TLS example

### ISSUE THREAD

**Issue by MartiniMoe** [kube-hetzner/kube-hetzner#109]
The TLS example configures a secret while at the same time providing annotations to let traefik request a certificate from lets encrypt:
https://github.com/kube-hetzner/kube-hetzner/blob/6f6de884ec1baace14b894e5ee1917ffa947e1ca/examples/tls/ingress.yaml#L12

If I get this right the line referencing the secret is wrong here? If thats the case I could do a pull request to fix the documentation and example.

**Comment by mysticaltech** [comment]
@MartiniMoe Yes, basically you also need to set this is your terraform.tfvars:

```
traefik_acme_tls = true
traefik_acme_email = "mail@example.com"
```

Or your cluster is already deployed, just copy this file https://github.com/kube-hetzner/kube-hetzner/blob/master/templates/traefik_config.yaml.tpl, and change it directly and re-apply.

As for the secrets, le will just use the name mentioned to create one for you. Am I missing something?

**Comment by MartiniMoe** [comment]
Hmm, when I tried it like this I got errors from Traefik saying the secret does not exist.
When I deleted the line containing the secret it works.

**Comment by MartiniMoe** [comment]
Okay, I created a pull request :) See #112
