### ISSUE TITLE
Metrics-Server unable to scrape metrics

### ISSUE THREAD

**Issue by MartiniMoe** [kube-hetzner/kube-hetzner#114]
Hi,

the metrics-server in my cluster is unable to scrape metrics from nodes:

```
I0305 08:15:26.352996       1 serving.go:341] Generated self-signed cert (/tmp/apiserver.crt, /tmp/apiserver.key)
I0305 08:15:26.719418       1 requestheader_controller.go:169] Starting RequestHeaderAuthRequestController
I0305 08:15:26.719485       1 shared_informer.go:240] Waiting for caches to sync for RequestHeaderAuthRequestController
I0305 08:15:26.719421       1 configmap_cafile_content.go:202] Starting client-ca::kube-system::extension-apiserver-authentication::client-ca-file
I0305 08:15:26.719520       1 shared_informer.go:240] Waiting for caches to sync for client-ca::kube-system::extension-apiserver-authentication::client-ca-file
I0305 08:15:26.719496       1 configmap_cafile_content.go:202] Starting client-ca::kube-system::extension-apiserver-authentication::requestheader-client-ca-file
I0305 08:15:26.719646       1 shared_informer.go:240] Waiting for caches to sync for client-ca::kube-system::extension-apiserver-authentication::requestheader-client-ca-file
I0305 08:15:26.720159       1 dynamic_serving_content.go:130] Starting serving-cert::/tmp/apiserver.crt::/tmp/apiserver.key
I0305 08:15:26.720267       1 secure_serving.go:202] Serving securely on :4443
I0305 08:15:26.720356       1 tlsconfig.go:240] Starting DynamicServingCertificateController
E0305 08:15:26.723158       1 scraper.go:139] "Failed to scrape node" err="Get \"https://10.2.0.1:10250/stats/summary?only_cpu_and_memory=true\": x509: certificate is valid for 127.0.0.1, 88.198.105.71, not 10.2.0.1" node="agent-big-0"
I0305 08:15:26.820176       1 shared_informer.go:247] Caches are synced for RequestHeaderAuthRequestController 
I0305 08:15:26.820185       1 shared_informer.go:247] Caches are synced for client-ca::kube-system::extension-apiserver-authentication::requestheader-client-ca-file 
I0305 08:15:26.820191       1 shared_informer.go:247] Caches are synced for client-ca::kube-system::extension-apiserver-authentication::client-ca-file 
I0305 08:15:27.267832       1 server.go:188] "Failed probe" probe="metric-storage-ready" err="not metrics to serve"
I0305 08:15:27.636114       1 server.go:188] "Failed probe" probe="metric-storage-ready" err="not metrics to serve"
I0305 08:15:28.269638       1 server.go:188] "Failed probe" probe="metric-storage-ready" err="not metrics to serve"
I0305 08:15:29.635527       1 server.go:188] "Failed probe" probe="metric-storage-ready" err="not metrics to serve"
I0305 08:15:31.635288       1 server.go:188] "Failed probe" probe="metric-storage-ready" err="not metrics to serve"
I0305 08:15:33.636699       1 server.go:188] "Failed probe" probe="metric-storage-ready" err="not metrics to serve"
I0305 08:15:35.635678       1 server.go:188] "Failed probe" probe="metric-storage-ready" err="not metrics to serve"
I0305 08:15:37.636936       1 server.go:188] "Failed probe" probe="metric-storage-ready" err="not metrics to serve"
I0305 08:15:39.635200       1 server.go:188] "Failed probe" probe="metric-storage-ready" err="not metrics to serve"
I0305 08:15:41.635422       1 server.go:188] "Failed probe" probe="metric-storage-ready" err="not metrics to serve"
E0305 08:15:41.711552       1 scraper.go:139] "Failed to scrape node" err="Get \"https://10.2.0.1:10250/stats/summary?only_cpu_and_memory=true\": x509: certificate is valid for 127.0.0.1, 88.198.105.71, not 10.2.0.1" node="agent-big-0"
E0305 08:15:56.722408       1 scraper.go:139] "Failed to scrape node" err="Get \"https://10.2.0.1:10250/stats/summary?only_cpu_and_memory=true\": x509: certificate is valid for 127.0.0.1, 88.198.105.71, not 10.2.0.1" node="agent-big-0"
E0305 08:16:11.698713       1 scraper.go:139] "Failed to scrape node" err="Get \"https://10.2.0.1:10250/stats/summary?only_cpu_and_memory=true\": x509: certificate is valid for 127.0.0.1, 88.198.105.71, not 10.2.0.1" node="agent-big-0"
E0305 08:16:26.707787       1 scraper.go:139] "Failed to scrape node" err="Get \"https://10.2.0.1:10250/stats/summary?only_cpu_and_memory=true\": x509: certificate is valid for 127.0.0.1, 88.198.105.71, not 10.2.0.1" node="agent-big-0"
```

My cluster only consists of that one big agent and 3 control nodes. Any idea whats happening here?

**Comment by phaer** [comment]
Hi @MartiniMoe,

Looks like your control planes certificate does not include its internal IP. This looks like a bug, but I don't have time to investigate correctly atm. If you do, please try if adding the following line to your control planes k3s config in https://github.com/kube-hetzner/kube-hetzner/blob/master/control_planes.tf#L45

```
tls-san = module.control_planes[0].private_ipv4_address
```

and re-provision. This should include the control planes private ip in the cert, but is curently untested.

**Comment by MartiniMoe** [comment]
Thanks, I will try that!
How can I re-provision easily? Or do I have to takedown everything and start over?

**Comment by phaer** [comment]
Should be sufficient to taint your first control node in this case.

**Comment by MartiniMoe** [comment]
Thanks. I added the line and let terraform recreate the control-node-0, but the problems persists :/

**Comment by phaer** [comment]
Does the resulting k3s config look correct? Did you check whether the certificate is generated correctly?  Did you try re-creating the cluster?
I sadly can't provide step-by-step instructions, you need to do some of the digging yourself  (or wait until someone else does) ;)

**Comment by mysticaltech** [comment]
@phaer The `tls-san` defaults to the `node-ip`, that's why I removed it while fixing another certificate issue that was just the node agents using their public IP as node-ip. So I believe, that `tls-san`, is not the problem, or is it?

**Comment by phaer** [comment]
@mysticaltech Could be, I am mostly guessing at this point!

> x509: certificate is valid for 127.0.0.1, 88.198.105.71, not 10.2.0.1" node="agent-big-0"

I interpret this error as saying that the metric server (on agent-big-0) is trying to contact the API server on 10.2.0.1, but its certificate is only signed for localhost and the external ip, not the internal control plane ip (10.2.0.1). So SAN sounds suspicious to me.

**Comment by mysticaltech** [comment]
Ahhh.... So we just need to add the external IP to the tls-san then!

**Comment by mysticaltech** [comment]
@MartiniMoe  you are probably using master from 48h ago... Just pull the latest changes, this is fixed already!

**Comment by MartiniMoe** [comment]
@mysticaltech Thanks, I already pulled and did a `terraform apply`. Can I fix this without recreating the cluster?

**Comment by phaer** [comment]
Can confirm that the metrics-server seems to be working in my just-deployed cluster (name-suffixes branch, but that shouldn't matter here)

**Comment by mysticaltech** [comment]
@MartiniMoe Yes probably, login via ssh to each agent (see in the readme). 

then:

systemctl stop k3s-agent

Then edit the /etc/rancher/k3s/config.yml

Change the server IP, basically all IPs to the private IP.

systemctl start k3s-agent

For each agents.

**Comment by MartiniMoe** [comment]
@mysticaltech Do I change `"server":` or `"node-ip":` or both?

**Comment by mysticaltech** [comment]
My bad all IPs that are not private must be. 

All should be 10.X.0.X...

As soon as you open the file, you will know!

**Comment by mysticaltech** [comment]
Maybe you need to drain and uncordon the node before.. I think it's best

**Comment by MartiniMoe** [comment]
I'm not sure what happened here. My agent has the private IP "10.1.0.1" in the config file, but actually it has "10.2.0.1" :confused:

**Comment by phaer** [comment]
What's your `network_ipv4_subnets` and `agent_nodepools`?

**Comment by MartiniMoe** [comment]
```
network_ipv4_subnets = {
  control_plane = "10.1.0.0/16"
  agent_big     = "10.2.0.0/16"
#  agent_small   = "10.3.0.0/16"
}

agent_nodepools = {
  agent-big = {
    server_type = "cpx21",
    count       = 1,
    subnet      = "agent_big",
  }
#  agent-small = {
#    server_type = "cpx11",
#    count       = 2,
#    subnet      = "agent_small",
#  }
}
```

**Comment by MartiniMoe** [comment]
If I change the agants IP in its config to its actual IP the node is shown as not ready afterwards in `kubectl get nodes`.

**Comment by mysticaltech** [comment]
Post you config.yaml file here please. You r server IP should be 10.1.0.1. And check the node events, with kubectl describe. What does it say? Also did you drain it and and cordon before?

**Comment by mysticaltech** [comment]
This is a misconfiguration and the problem has been fixed a few days ago, so removing the above labels.

**Comment by mysticaltech** [comment]
Any updates on this @MartiniMoe?

**Comment by MartiniMoe** [comment]
Ah yes, sorry for the late reply, I was a little busy.

So, this is my network
![image](https://user-images.githubusercontent.com/7438779/157008604-5420f165-5eab-42b2-92b0-5c7fa7858648.png)

This is the `config.yaml` on agent-big-0:
```
static:~ # cat /etc/rancher/k3s/config.yaml
"flannel-iface": "eth1"
"kubelet-arg": "cloud-provider=external"
"node-ip": "10.1.0.1"
"node-label":
- "k3s_upgrade=true"
"node-name": "agent-big-0"
"server": "https://10.1.0.1:6443"
"token": "<token>"
```

There are no events:
```
~ ❯ kubectl describe node agent-big-0
[...]
Events:              <none>
```

Regarding draining and cordon, I tried to do it, but it did not really work, because I had to much workload in the cluster. I then deleted some deployments, tried again and made the changes to `config.yaml`. To be honest at this point I'm not exactly sure if the node was drained then :confused:

**Comment by mysticaltech** [comment]
The node-ip is wrong, it should be the private ip of you server so 10.2.0.X form.

**Comment by mysticaltech** [comment]
The node-ip is wrong, it should be the private ip of you server so 10.2.0.X form.

**Comment by MartiniMoe** [comment]
Thank you so much! Now it looks okay :)
