### ISSUE TITLE
Disable Traefik ingress controller & lb

### ISSUE THREAD

**Issue by oujonny** [kube-hetzner/kube-hetzner#122]
Hi guys
Thanks to all contributors to this amazing project!

Is it possible to disable the treafik ingress controller at all? I would prefer using nginx-ingress or istio-gateway as ingress solution. For that, I didn't need the Loadbalancer and the treafik installation.

I'm also open to contributing such a toggle function but would need some inputs on how to implement it the best way. :)

cheers,
Johann Schley

**Comment by mysticaltech** [comment]
@mnencia I believe that one is of interest to you too!

**Comment by mnencia** [comment]
I think we should expose flags to disable traefik and also metrics server (you may want to use prometheus-adapter instead)

**Comment by mysticaltech** [comment]
Definitely, that's a quick add too!

**Comment by paulwollgast** [comment]
Hello guys, also from my side big thanks for that project and +1 to @oujonnys request, I'm also planning to use nginx and/or istio ingress so that would be nice!

**Comment by mysticaltech** [comment]
@paulwollgast Thanks for sharing! Definitely, that's a low-hanging fruit, and will be done shortly.

**Comment by oujonny** [comment]
Hi Guys
Thanks for all your anwnsers! 
I will open an PR now to introduce the possibility to disable traefik & metrics-server. By default traefik will be **disabled** and metrics-server enabled.

**Comment by mysticaltech** [comment]
Closed in #127
