### ISSUE TITLE
Provisioning failing in CI

### ISSUE THREAD

**Issue by paulwollgast** [kube-hetzner/kube-hetzner#124]
Hello everybody,

first and foremost thanks again for this amazing project!

I encountered a problem when trying to deploy from within a CI pipeline (Github Actions, I'd be happy to contribute the final Action when everything is ready), while the very same code works when kicked off locally. I get the following error:

<img width="711" alt="Bildschirmfoto 2022-03-10 um 18 40 18" src="https://user-images.githubusercontent.com/37050770/157723807-f8b797ac-3994-44b2-a049-5e651b820d2e.png">

Note: I didn't touch the provider configuration contained in versions.tf of the root module despite adding a terraform backend (S3 + DynamoDB):

```
terraform {
  required_providers {
    github = {
      source  = "integrations/github"
      version = ">= 4.0.0, < 5.0.0"
    }
    hcloud = {
      source  = "hetznercloud/hcloud"
      version = ">= 1.0.0, < 2.0.0"
    }
    local = {
      source  = "hashicorp/local"
      version = ">= 2.0.0, < 3.0.0"
    }
    remote = {
      source  = "tenstad/remote"
      version = "~> 0.0.23"
    }
  }

  backend "s3" {
    bucket = "<omitted>"
    key = "preview/terraform.tfstate"
    region = "eu-west-1"
    encrypt = true
    kms_key_id = "<omitted>"
    dynamodb_table = "tf-remote-state-lock"
  }
}
```

Does somebody have an idea what the reason might be?

**Comment by mysticaltech** [comment]
@phaer Any ideas?

**Comment by mnencia** [comment]
I use the backend s3 in my deployments, and it works. I do not think it is the culprit.

**Comment by mnencia** [comment]
I may have a clue. On my machine, github API authentication is done automatically through the os keyring. Try following the instructions here to make sure your authentication works correctly https://registry.terraform.io/providers/integrations/github/latest/docs#authentication

**Comment by paulwollgast** [comment]
@mnencia I'll get back to this as soon as possible and let you know, thank you very much for the hint!

**Comment by paulwollgast** [comment]
Update: That was it, I incorrectly assumed the access is provided by the environment vars already which wasn't the case.
Simply adding the explicit provider config (necessary if working with private repositories) solved the issue:

```sh
terraform {
  required_providers {
    github = {
      source  = "integrations/github"
      version = ">= 4.0.0, < 5.0.0"
    }
    hcloud = {
      source  = "hetznercloud/hcloud"
      version = ">= 1.0.0, < 2.0.0"
    }
    local = {
      source  = "hashicorp/local"
      version = ">= 2.0.0, < 3.0.0"
    }
    remote = {
      source  = "tenstad/remote"
      version = "~> 0.0.23"
    }
  }

  backend "s3" {
    bucket = "<omitted>"
    key = "preview/terraform.tfstate"
    region = "eu-west-1"
    encrypt = true
    kms_key_id = "<omitted>"
    dynamodb_table = "tf-remote-state-lock"
  }
}

provider "github" {
  owner = "<omitted>" //Add the organization or user name here
  token = var.GITHUB_TOKEN
}
