### ISSUE TITLE
Use of deprecated Template Provider causes error on Apple Silicon (M1)

### ISSUE THREAD

**Issue by cliffred** [kube-hetzner/kube-hetzner#128]
Commit dbc6dbf0aaf0bc82335d81af1cf383d664e3f303 introduced a dependency on the deprecated hashicorp/template provider. This provider does not work on Apple Silicon, resulting in the following error on `terraform init`:
```
Error: Incompatible provider version
 
Provider registry.terraform.io/hashicorp/template v2.2.0 does not have a package available for your current platform, darwin_arm64.

Provider releases are separate from Terraform CLI releases, so not all providers are available for all platforms. Other versions of this provider may have different platforms supported.
```

https://github.com/hashicorp/terraform/issues/27257#issuecomment-825102330 mentions a workaround, but it's probably better to stop using this deprecated provider.

**Comment by mnencia** [comment]
Fixed in #129
