### ISSUE TITLE
'sleep' is not recognized as an internal or external command

### ISSUE THREAD

**Issue by egahmad** [kube-hetzner/kube-hetzner#21]
After runing the cluster I get this,

╷
│ Error: local-exec provisioner error
│
│   with hcloud_server.first_control_plane,
│   on master.tf line 44, in resource "hcloud_server" "first_control_plane":
│   44:   provisioner "local-exec" {
│
│ Error running command 'sleep 60 && ping 138.201.89.68 | grep --line-buffered "bytes from" | head -1 && sleep 100 &&
│ scp -o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null -i ./keys/id_rsa
│ rancher@138.201.89.68:/etc/rancher/k3s/k3s.yaml ./kubeconfig.yaml
│ sed -i -e 's/127.0.0.1/138.201.89.68/g' ./kubeconfig.yaml
│ ': exit status 1. Output: 'sleep' is not recognized as an internal or external command,
│ operable program or batch file.

I'm trying to access the server but I have another problem, I have a generated keys using puttygen, I can't connect to the controlplane . does anyine know how to export key from keygen in a proper format? i'm using windows 10

**Comment by mysticaltech** [comment]
Hello @egahmad, please try from the linux subsystem in windows, this is not compatible with the windows command line.
