### ISSUE TITLE
use of existing https certificates

### ISSUE THREAD

**Issue by fraank** [kube-hetzner/kube-hetzner#24]
With [https://console.hetzner.cloud/projects/.../security/certificates](https://console.hetzner.cloud/projects/.../security/certificates) there is a comfortable interface for managing https certificates over different contexes.

Is there any way to use them with kube-hetzner?

**Comment by mysticaltech** [comment]
Hey @fraank, I believe that working with certificates that are stored in Hetzner is out of context here. Basically, all you need to do is configure your ingress definition to use the certificate you want, that is stored or generated in Kubernetes itself. 

You never ever have to touch the LB manually, it will just show up there automatically and all just works.

Please have a look at a previous issue https://github.com/kube-hetzner/kube-hetzner/issues/18 on the subject where you'll find a few examples. Good luck!

**Comment by fraank** [comment]
Yes, using ingress could be a solution.

My first thought was, if it is possible to change protocols of LB from tcp:80-> http:80 and tcp:443 -> https:80(or 443)?
I can attach many certificates at the loadbalancer service interface when switching protocols to https.

A simple test switching incoming protocol from tcp to http turnes out, that it makes the service unhealthy. the same with https.

**Comment by mysticaltech** [comment]
Yes, but you have understand that the LB is created by the ingress controller with its required specs, so if you change it manually later on, it's no longer has the required specs and becomes unhealthy. 

So any changes you do to the LB must be through the ingress system! And since by default it's configured to use proxy protocol, you just need to configure the ingress definitions well and everything just works, including SSL. In the other issue above mentioned above, you'll find an example ingress definition. Just try it, you'll be surprised! :)

**Comment by mysticaltech** [comment]
@fraank No bother at all. It's definitely a good discussion to have.

From what I see, it appears you are not creating your certificate as a Kubernetes secret? Yet you are calling it from your ingress definition as a secret in Kubernetes.

My apologies frank, I had pasted the wrong command in the other [issue](https://github.com/kube-hetzner/kube-hetzner/issues/18#issuecomment-1012540840), now rectified. There is no `hcloud create` needed at all, the secret needs to be created in Kubernetes only, with the following command:

```
kubectl create secret tls mydomain-de --key origin-ca.pk --cert origin-ca.crt
```

Now it will work! 🤞

**Comment by fraank** [comment]
Oh, ok. Now it makes more sense.

Unfortunately hetzner don't let us download the .pk and .crt directly. I thought I can use parts of [this](https://github.com/vadimkim/cert-manager-webhook-hetzner), to download and update the cert via API-Request.

I cannot believe I'm the first one doing this, but cannot find any notes about that.

**Comment by mysticaltech** [comment]
If I were you, just forget Hetzner certificates, Cloudflare is great, or just LetsEncrypt!

**Comment by fraank** [comment]
Ok, I got an official statement from Hetzner that [Cloud Control Manager](https://github.com/hetznercloud/hcloud-cloud-controller-manager) cannot be used for Ingress-Services. They recommended me, to implement it by myself but cannot give any guarantee that it will finally work.

I think I will tryout Cloudflare. Thanks for your patience and input :-). I guess this ticket can be closed.

**Comment by mysticaltech** [comment]
Great! Thanks for clarifying, you won't regret it, Cloudflare rocks!
