### ISSUE TITLE
Why are Server not Put into a Placement Group?

### ISSUE THREAD

**Issue by a0n** [kube-hetzner/kube-hetzner#31]
When I Setup a Cluster it seems that the server are not created with a Placement Group of the Type "Spread".
This should be common practice though to maximise availability should the host machine fail. 

There is a fairly recent [Tutorial](https://community.hetzner.com/tutorials/k3s-glusterfs-loadbalancer) on Hetzner Community that mentions that.

**Comment by mysticaltech** [comment]
Thanks, @a0n, found the definition [here](https://docs.aws.amazon.com/AWSEC2/latest/UserGuide/placement-groups.html). Definitely important, to add resiliency to the system. Will do as soon as I can, but if you want to take a shot, a PR would be very welcome.
