### ISSUE TITLE
hcloud_network_subnet.k3s: Still destroying

### ISSUE THREAD

**Issue by exocode** [kube-hetzner/kube-hetzner#38]
Somehow `terraform destroy` keeps hanging on destroying the network:

```
hcloud_placement_group.k3s_placement_group: Destruction complete after 0s
hcloud_firewall.k3s: Destruction complete after 0s
...
..
.
hcloud_network_subnet.k3s: Still destroying... [id=1352246-10.0.0.0/16, 10m40s elapsed]
hcloud_network_subnet.k3s: Still destroying... [id=1352246-10.0.0.0/16, 10m50s elapsed]
hcloud_network_subnet.k3s: Still destroying... [id=1352246-10.0.0.0/16, 11m0s elapsed]
hcloud_network_subnet.k3s: Still destroying... [id=1352246-10.0.0.0/16, 11m10s elapsed]
hcloud_network_subnet.k3s: Still destroying... [id=1352246-10.0.0.0/16, 11m20s elapsed]
hcloud_network_subnet.k3s: Still destroying... [id=1352246-10.0.0.0/16, 11m30s elapsed]
hcloud_network_subnet.k3s: Still destroying... [id=1352246-10.0.0.0/16, 11m40s elapsed]

```

I also tried to reapply `terraform destroy`
When I manually delete the network in the UI, it finishes a few seconds later

**Comment by mysticaltech** [comment]
@exocode Just issue `hcloud load-balancer delete traefik` before, or delete the LB in the UI manually if you prefer. Then retry!

**Comment by exocode** [comment]
ok. Simply thought that tearing down could also be that clean like spinning up

**Comment by mysticaltech** [comment]
Yes, there is nothing we can do about that because the LB is provisioned by Traefik, not Terraform (and that's a good thing). So we need to kill it separately. It's in the docs https://github.com/kube-hetzner/kube-hetzner#takedown. Glad it's resolved!
