### ISSUE TITLE
Control-plane-0 should be tainted with 'node-role.kubernetes.io/master=true:NoSchedule'

### ISSUE THREAD

**Issue by valb3r** [kube-hetzner/kube-hetzner#39]
Suggest to taint master node (control-plane-0) with `node-role.kubernetes.io/master=true:NoSchedule` as currently it is not tainted. 
I.e. adding 
```
  # Taint Control Plane as master node to avoid scheduling of workloads here
  provisioner "local-exec" {
    command = <<-EOT
      kubectl taint nodes "${self.name}" node-role.kubernetes.io/master=true:NoSchedule
    EOT
  }
```
to master.tf

Because of being not tainted, workload pods can get placed on `control-plane-0` and disrupt cluster 
(i.e. Cassandra or HDFS pod placed on `control-plane-0` with almost 100% guarantee disrupts cluster)

**Comment by mysticaltech** [comment]
Ok, definitely a good thing to make optional! I for instance like to all nodes for computing, but am not using things like Cassandra! So will give the option definitely 🙏

**Comment by phaer** [comment]
Thanks for catching that @valb3r! I think keeping it optional, but tainting the control nodes by default would be the best choice as, in my understanding that's generally the expected behavior for kubernetes clusters? Could be different for k3s though?

**Comment by valb3r** [comment]
AFAIK, it is must have for production k8s clusters.
For k3s i.e. - https://gabrieltanner.org/blog/ha-kubernetes-cluster-using-k3s also enforces master node taints. 
As here we are talking about Hetzner and therefore cheap clusters I would agree wit @mysticaltech that it is optional parameter depending on workload, but it should be documented

**Comment by mysticaltech** [comment]
Definitely, will do, but in the meantime, just shoot a PR adding a variable for that if you can, enabled by default indeed.

**Comment by mysticaltech** [comment]
Added by default, thanks again @mnencia!
