### ISSUE TITLE
local-exec provisioner error

### ISSUE THREAD

**Issue by unitw** [kube-hetzner/kube-hetzner#5]
i followed the instructions from the readme file and the error 
`local-exec provisioner error
 Error running command 'kubectl -n kube-system create secret generic hcloud
 exit status 1. Output: Unable to connect to the server: dial tcp
`
pops up.  
Am i missing anything?

**Comment by mysticaltech** [comment]
Hey @unitw, are you using a clean Hetzner project? And please take a screenshot. Also, did you modify anything in the code? Especially the k3os config templates? Because what I am seeing here, is an error reaching the server. 

Probably what is happening is that your SSH public key is not being correctly copied to the server. Did you put the right key pair? Also, try pinging the server IP, see if it connects.

**Comment by mysticaltech** [comment]
Your [terraform.tfvars](terraform.tfvars) should have the to your SSH public key, and private key. Both path should be correct!

**Comment by unitw** [comment]
I did not modify any files and followed the instructions. I even switched from Windows to Linux and it failed with 
   
       hcloud_server.first_control_plane (local-exec): Unable to connect to the server: dial tcp xxx:6443: i/o timeout
       Error: local-exec provisioner error
       with hcloud_server.first_control_plane,
       on master.tf line 51, in resource "hcloud_server" "first_control_plane":
       51:   provisioner "local-exec" {
      
       Error running command 'kubectl -n kube-system create secret generic hcloud
       --from-literal=token=xxx --from-literal=network=k3s-net
       --kubeconfig ./kubeconfig.yaml
       kubectl apply -f ./manifests/hcloud-ccm-net.yaml --kubeconfig ./kubeconfig.yaml
       kubectl -n kube-system create secret generic hcloud-csi
       --from-literal=token=xxx --kubeconfig ./kubeconfig.yaml
       kubectl apply -f https://raw.githubusercontent.com/hetznercloud/csi-driver/master/deploy/kubernetes/hcloud-csi.yml
       --kubeconfig ./kubeconfig.yaml
       ': exit status 1. Output: error: failed to create secret Post
       "https://xxx:6443/api/v1/namespaces/kube-system/secrets?fieldManager=kubectl-create": dial tcp
       xxx:6443: i/o timeout
       Unable to connect to the server: dial tcp xxx:6443: i/o timeout
       error: failed to create secret Post
       "https://xxxx:6443/api/v1/namespaces/kube-system/secrets?fieldManager=kubectl-create": dial tcp
       xxx:6443: i/o timeout
       Unable to connect to the server: dial tcp xxx:6443: i/o timeout
      
again. I tried it multiple times with different projects..
At the end i created the cluster by hand.

**Comment by mysticaltech** [comment]
SSH wasn't connecting, generating a fresh key pair and, pointing to it in the config would have worked normally.

**Comment by mysticaltech** [comment]
Sorry to hear you had to do it manually.
