### ISSUE TITLE
Validate node reboots healthy

### ISSUE THREAD

**Issue by mysticaltech** [kube-hetzner/kube-hetzner#56]
@mnencia Have created like you a cluster of 3 controls and 2 agents. And to accelerated the process, have issued `touch /var/run/reboot-required` on all five of them, to simulate a post-update scenario. 

I will report back on what happens after that. Please do not hesitate to share your findings here too.

**Comment by mysticaltech** [comment]
As you stated sooner, Rancher confirms that for HA, the number of control plane nodes must be odd, so a minimum of 3 indeed. Let's see! 🤞

Source: https://rancher.com/docs/k3s/latest/en/installation/ha-embedded/

**Comment by mysticaltech** [comment]
Seems to have worked like a charm, the `last reboot` command confirms it on the nodes, only node remaining to reboot is `k3s-control-plane-2`,

![ksnip_20220209-230731](https://user-images.githubusercontent.com/518555/153298512-dea3dc57-4eb9-41b2-a0f7-6c656c9b6419.png)

**Comment by mysticaltech** [comment]
@phaer @mnencia Worked like a charm! 🍾 `k3s-control-plane-2` finally rebooted and was admitted back the cluster like a prince! :)

![ksnip_20220209-234127](https://user-images.githubusercontent.com/518555/153303230-bb019e48-09cf-4c6a-ba46-f2fe23da426f.png)

**Comment by mysticaltech** [comment]
Interesting learning, was that it did not reboot because there was a lock acquired on `k3s-control-plane-1` already, so it waited the next hour to reboot.

**Comment by mysticaltech** [comment]
As soon as one of you validated the above with your own cluster, we'll be good to go into master.

**Comment by mysticaltech** [comment]
Folks, thanks to the "new pattern" for waiting for stuff without sleep, that I learned from @mnencia, was able to kill most `sleep` and we are now a lot faster! I believe in under 5 minutes, it is up and running for 5 nodes ⚡

**Comment by mysticaltech** [comment]
I believe we are good to merge to master, what do you think?

**Comment by mnencia** [comment]
Ok for me, my cluster worked like a charm..
