### ISSUE TITLE
Make sure the hostname does not get superseeded by the transient one

### ISSUE THREAD

**Issue by mysticaltech** [kube-hetzner/kube-hetzner#57]
We are setting the hostnane via ignition by editing `/etc/hostname`, that set the static hostname correctly, but it gets superseded by the transient one. 

I tried forcing the transient one with DHCP_HOSTNAME=hostname in ifcfg files, but to no avail.

![ksnip_20220210-012330](https://user-images.githubusercontent.com/518555/153313432-500526cc-11c1-4169-9415-73f1430f6948.png)

**Comment by mysticaltech** [comment]
However` hostnamectl set-hostname <hostname>` seems to persist, so will try with that.

**Comment by mysticaltech** [comment]
Fixed in the last pushed to staging, thanks to the command being applied.

**Comment by mysticaltech** [comment]
With the above command, it survives reboots, but not updates, the `static` transient name comes back!

**Comment by phaer** [comment]
@mysticaltech  I had not looked into this before, but if read `hostnamectl(1)` correctly, your command only sets the "pretty" hostname, right? 
Does `hostnamectl --static set-hostname <hostname>` survive upgrades? I don't have a long-running cluster to test atm :D

**Comment by mysticaltech** [comment]
Am not sure if I have tested the above with --static. But without it, it survived reboots, but not upgrades!

However have found this [resource](http://www.scalingbits.com/aws/sap/suse/hostname) just yesterday, it could have the solution for this, basically including the hostname in `/etc/hosts` and adding `preserve_hostname: true` to `/etc/cloud/cloud.cfg`.

**Comment by mysticaltech** [comment]
Interesting... https://man7.org/linux/man-pages/man1/hostnamectl.1.html
![ksnip_20220219-123008](https://user-images.githubusercontent.com/518555/154799002-fc6cccf8-3e6c-470f-8708-baaaea318830.png)

**Comment by phaer** [comment]
> However have found this [resource](http://www.scalingbits.com/aws/sap/suse/hostname) just yesterday, it could have the solution for this, basically including the hostname in /etc/hosts and adding preserve_hostname: true to /etc/cloud/cloud.cfg, on top hostnamectl.

Ah yes, that sounds about right! Don't know anything about microos implementation, but I did need `preserve_hostname` with cloud-init on another platform for the same behavior (Debian VMs with Proxmox VEs cloud-init implementation)

**Comment by mysticaltech** [comment]
Yeah, me too. MicroOS does do cloud-init, so maybe that is what resets the hostname on upgrades?! No idea, but worth a shot hehe.

**Comment by mysticaltech** [comment]
Just tried with `hostnamectl set-hostname --static` let's see in a few days!

About the rest, the system does not have an `etc/cloud` directory. Was also not able to find `cloud.cfg` on the filesystem.

**Comment by mysticaltech** [comment]
Otherwise, we can run that command at boot time and that's it.

**Comment by mnencia** [comment]
I can confirm that the image we use doesn't include cloud-init. It is only available in the OpenStack flavor.

**Comment by mysticaltech** [comment]
This is what happen, it did it again, at some point the $HOST global variable takes the name of the transient hostname that shows up out of the blue.

![ksnip_20220221-170019](https://user-images.githubusercontent.com/518555/154989884-f40543bc-c2a2-4469-b4fb-1f16556fd1b1.png)

**Comment by mysticaltech** [comment]
Basically, by doing that, we would force the value of the static hostname and the HOST global variable, the rest, we do not care. Personally, I believe that to be good enough.

**Comment by mysticaltech** [comment]
As soon as I can, will also try editing the /etc/hosts file too, which is something we have not tried before.

![ksnip_20220221-170735](https://user-images.githubusercontent.com/518555/154991263-9e29211d-956f-4d8d-9a86-55cbb76037e7.png)

**Comment by mysticaltech** [comment]
Will try adding `127.0.0.1 <name>` at the top of the hosts file on top of issuing hostname set-hostname, maybe that would solve it for us once and for all.

**Comment by mysticaltech** [comment]
Should be fixed now, turns out we needed to set NETCONFIG_NIS_SETDOMAINNAME to "no" in /etc/sysconfig/network/config.
