### ISSUE TITLE
Move to k3s in binary form

### ISSUE THREAD

**Issue by mysticaltech** [kube-hetzner/kube-hetzner#60]
@mnencia @phaer Had a very interesting [conversation with Richard Brown](https://twitter.com/mysticaltech/status/1491692860764266504), he says no RPM is needed and that the btrfs sub-volumes are writable so we can just swap the binary, and voila!

So we can go back to MicroOS vanilla, and just use the k3s binaries from https://github.com/k3s-io/k3s/releases, as is. Maybe have a timer that checks for a new release, if there is one, touch /var/run/reboot-required, Kured drains the node, and reboots, and on reboot, we have a small script that does the swap :)

Let's see - I will try to give it a shot this weekend, but please do not hesitate if you feel inspired.

Also, welcome to the team if you'll accept, just sent you the invitation :) 🍾

**Comment by phaer** [comment]
> In git, see the commit named "before move to k3os".

I think this refers to https://raw.githubusercontent.com/kube-hetzner/kube-hetzner/f308220bfe1236d735172e11b7f1841ca2597d14/manifests/upgrade/plans.yaml ?

**Comment by mysticaltech** [comment]
You got it right, Kured for OS, it manages everything and it works.

And indeed system-upgrade-controller for k3s, and it also manages everything.

Yes, ideally it would have been great to use only Kured, if the RPM channel now used (devel:kubic/k3s) gave recent versions and was updated regularly. But that is not the case. Also Richard Brown basically admitted that it is not a priority and that the best way to install k3s would be to use the install script, which I verified and it will be ideal indeed.

So we have left with k3s install with the vanilla install script (that supports MicroOS, between, it tests for it in the code) and either a custom way to upgrade and also create a /var/run/reboot-required file, and have Kured do the reboot, and some custom mechanism to switch the binary at boot.

Or we just use system-ugprade-controller that will do everything for us, even without reboot, and fully independent of Kured. It will also execute rarely, just when new stable releases come down.

So I really think that in our case, it's still something really solid that we're planning to do here. Kured for OS, system-upgrade-controller for k3s, fresh from Github, without middlemen.

**Comment by mysticaltech** [comment]
Alright, folks, this is done and ready for testing, see the `k3s-install` branch.

It does take twice the time of the other method because now k3s does not come pre-installed, and one more reboot is required after it installs, because of the k3s-selinux RPM package, for the new snapshot to take effect.

However, clusters only get deployed once, and then they are either agile or stuck. I prefer the former!

It's also important to move to that because the k3s MicroOS image is not even official.

Last but not least, with this new method, k3s automatically upgrades and follows the stable channel unless a node label is changed to `k3s_upgrade=false`.

You can also the update channel you want, latest, stable, testing, or even target specific versions. See https://rancher.com/docs/k3s/latest/en/upgrades/basic/ and https://update.k3s.io/v1-release/channels

![ksnip_20220216-042403](https://user-images.githubusercontent.com/518555/154191730-3b2a9565-a619-4038-848f-6c294e430523.png)

**Comment by mysticaltech** [comment]
The next step will be the test the k3s automatic upgrade by changing the upgrade channel from `stable` to `latest` in `plans.yaml` and applying it again. By doing so, we should witness an upgrade to 1.23.x

**Comment by mysticaltech** [comment]
kubectl get nodes
![ksnip_20220216-051942](https://user-images.githubusercontent.com/518555/154195623-f7ed2a44-53e2-4169-947a-9e7583567e82.png)

**Comment by mysticaltech** [comment]
kubectl get pods -A

![ksnip_20220216-052200](https://user-images.githubusercontent.com/518555/154195785-b668fcd4-bcfd-4486-b581-02e4c2c6aa2b.png)

**Comment by mysticaltech** [comment]
The next step will be to test the k3s automatic upgrade by changing the upgrade channel from `stable` to `latest` in `plans.yaml` and applying it again. By doing so, we should witness an upgrade to 1.23.x. Will do ASAP.

**Comment by mysticaltech** [comment]
Ok, so just following the latest channel did not produce upgrade jobs, probably because it waits for new releases. But setting the version I wanted manually... I replace the `channel` like in the plans by `version` and Boom!

![ksnip_20220216-113313](https://user-images.githubusercontent.com/518555/154247319-7e453359-dcf7-4b1e-8115-4d8253a80c8d.png)

**Comment by mysticaltech** [comment]
While it did the upgrades for each node, concurrency 1.

![ksnip_20220216-112919](https://user-images.githubusercontent.com/518555/154247606-1cf77128-e91b-4cc8-90d7-6fb4a425e9f5.png)

And after having completed:

![ksnip_20220216-113054](https://user-images.githubusercontent.com/518555/154247702-89977606-72ee-486d-af8b-06a0497717a6.png)

**Comment by mysticaltech** [comment]
kubectl get plans -n system-upgrade

![ksnip_20220216-113228](https://user-images.githubusercontent.com/518555/154247894-2a41b93a-9e4d-4e14-ab76-b3eaed243783.png)

**Comment by mysticaltech** [comment]
kubectl get jobs -n system-upgrade

![ksnip_20220216-113150](https://user-images.githubusercontent.com/518555/154247949-dc7dc2cc-e5ab-4e77-a927-3016a3724286.png)

**Comment by mysticaltech** [comment]
Now, will wait for a reboot by Kured to happen. Looking forward to any feedback.

**Comment by mysticaltech** [comment]
Good news! We can probably get away without the second reboot if we use a combustion script to install the k3s-selinux RPM package. Will try ASAP.

**Comment by mysticaltech** [comment]
Even better would be to install k3s through [combustion](https://en.opensuse.org/Portal:MicroOS/Combustion) itself. That would gain us some time, as indeed it would not require a second reboot, it just boots into the new snapshot.

**Comment by mysticaltech** [comment]
Just to confirm that it also rebooted with Kured after a MicroOS upgrade like a charm. Both systems work completely separately without interference.

**Comment by mysticaltech** [comment]
Ok, called the whole k3s install from combustion, it fails. Probably because the right paths are not available yet. Will try going just for the RPM, in the hope of avoiding the necessity of a second reboot.

![ksnip_20220217-083346](https://user-images.githubusercontent.com/518555/154427597-fd92d54f-af50-4da9-b2a5-9b114e3ee6ab.png)

**Comment by mysticaltech** [comment]
Finally, `k3s-selinux` is being installed via combustion on MicroOS, and that indeed removes the need for the second reboot.

```
Loading repository data...
Reading installed packages...
Resolving package dependencies...
The following NEW package is going to be installed:
  k3s-selinux
1 new package to install.
Overall download size: 19.9 KiB. Already cached: 0 B. After the operation, additional 84.3 KiB will be used.
Continue? [y/n/v/...? shows all options] (y): y
Retrieving package k3s-selinux-0.4-1.sle.noarch (1/1),  19.9 KiB ( 84.3 KiB unpacked)
Checking for file conflicts: [...done]
(1/1) Installing: k3s-selinux-0.4-1.sle.noarch [......done]
Executing %posttrans script 'k3s-selinux-0.4-1.sle.noarch.rpm' [....done]
Application returned with exit status 0.
Transaction completed.
tukit 3.6.2 started
ptions: close 2
Failure (dbus fatal exception).
New default snapshot is #2 (/.snapshots/2/snapshot).
Transaction completed.
Please reboot your machine to activate the changes and avoid data loss.
New default snapshot is #2 (/.snapshots/2/snapshot).
```

**Comment by mysticaltech** [comment]
Here's a forced upgrade of k3s 
![ksnip_20220217-220751](https://user-images.githubusercontent.com/518555/154571062-4e8d573d-b959-48b8-b638-4d68dad053d1.png)
to a specific version, working like a charm!

**Comment by mysticaltech** [comment]
Merged into master!
