### ISSUE TITLE
traefik ingress: Skipping service: no endpoints found

### ISSUE THREAD

**Issue by TimHeckel** [kube-hetzner/kube-hetzner#73]
Hi again :) So...I thought I understood, but I continue to have issues setting up simple ingress routes. I understand if this is out of scope for the kube-hetzner project, as it may likely just be a traefik configuration that I don't understand. In this scenario, I have installed the `whoami` helm chart:

```
helm repo add cowboysysop https://cowboysysop.github.io/charts/
helm install my-release cowboysysop/whoami
```

And I can see the `ingress`, `service`, and `pod` deployed all correctly into the default namespace, and port forwarding on the service or pod displays the whoami information, but the external route (https://whoami.site.com) returns an empty reply, like it was never 'caught' via the ingress, I keep getting these messages in the traefik pod's log:

`
level=error msg="Skipping service: no endpoints found" ingress=whoami-1645104801 namespace=default serviceName=whoami-1645104801 servicePort="&ServiceBackendPort{Name:,Number:80,}" providerName=kubernetes
`

As always, any help is much appreciated.

**Comment by mysticaltech** [comment]
If I were you, try to edit the ingress manually, making sure it points to the right service, and also displays the right certificates to the outside world, if automatic letsencrypt is not configured.

You need to verify the whole logical chain. Deployment, Pod, Service, and Ingress. And `kubectl describe` each one, and `kubectl logs` each container, including Traefik, to really get a picture of where it is failing and why.

**Comment by TimHeckel** [comment]
Closing this - the ingress worked with the new deploy - I'm suspicious of the `ingressClassName` property on the `Ingress` definition - I haven't nailed down a pattern, but it seems like `traefik` shouldn't be used in this deployment scenario - leaving it blank made my whoami demo work (and also showed the attached lb ip next to the ingress). When I supplied that, then the ingress didn't work...

**Comment by mysticaltech** [comment]
Awesome!!
