### ISSUE TITLE
terraform initialization stops after Install MicroOS and restart

### ISSUE THREAD

**Issue by drackows** [kube-hetzner/kube-hetzner#89]
I've set up terraform.tfvars with my hcloud_token, public_key, private_key, and:

```
location                  = "nbg1" # change to `ash` for us-east Ashburn, Virginia location
network_region            = "eu-central" # change to `us-east` if location is ash
agent_server_type         = "cx11"
control_plane_server_type = "cpx11"
lb_server_type            = "lb11"

servers_num               = 1
agents_num                = 0
# only one server is chosen because all servers has the same issue so I tried to focus on only one
```

just after success steps in host/main.tf:
```
  # Install MicroOS
  # Issue a reboot command
```
I can see:
```
module.first_control_plane.hcloud_server.server (local-exec): Executing: ["/bin/sh" "-c" "until ssh -o UserKnownHostsFile=/dev/null -o StrictHostKeyChecking=no -i /Users/drackowski/.ssh/id_rsa -o ConnectTimeout=2 root@88.198.206.252 true 2> /dev/null\ndo\n  echo \"Waiting for MicroOS to reboot and become available...\"\n  sleep 3\ndone\n"]
module.first_control_plane.hcloud_server.server (local-exec): Waiting for MicroOS to reboot and become available...
module.first_control_plane.hcloud_server.server: Still creating... [2m10s elapsed]
module.first_control_plane.hcloud_server.server (local-exec): Waiting for MicroOS to reboot and become available...
...
...
...
module.first_control_plane.hcloud_server.server: Provisioning with 'remote-exec'...
module.first_control_plane.hcloud_server.server (remote-exec): Connecting to remote host via SSH...
module.first_control_plane.hcloud_server.server (remote-exec):   Host: .......
module.first_control_plane.hcloud_server.server (remote-exec):   User: root
module.first_control_plane.hcloud_server.server (remote-exec):   Password: false
module.first_control_plane.hcloud_server.server (remote-exec):   Private key: true
module.first_control_plane.hcloud_server.server (remote-exec):   Certificate: false
module.first_control_plane.hcloud_server.server (remote-exec):   SSH Agent: true
module.first_control_plane.hcloud_server.server (remote-exec):   Checking Host Key: false
module.first_control_plane.hcloud_server.server (remote-exec):   Target Platform: unix
```

Error response is:
```
╷
│ Error: remote-exec provisioner error
│
│   with module.first_control_plane.hcloud_server.server,
│   on modules/host/main.tf line 60, in resource "hcloud_server" "server":
│   60:   provisioner "remote-exec" {
│
│ timeout - last error: dial tcp ........:22: i/o timeout
╵
```

When I'm trying to ssh to this machine it's not responding "timed out" after long time

On server console I can see welcome message from openSUSE with few SSH host keys and "static login: "
![Screenshot 2022-02-21 at 21 32 47](https://user-images.githubusercontent.com/3673348/155023445-0220fc14-fe80-4955-9731-877a71091dc3.png)

Do you know what can I check there else to diagnose what has happened? 😅

Full terraform apply console output is in attachment [full console output.txt](https://github.com/kube-hetzner/kube-hetzner/files/8111964/full.console.output.txt)

**Comment by mysticaltech** [comment]
@drackows There is a timeout of 120 in the master.tf file, just search 120 and you will find it, double that, destroy and retry please.

**Comment by drackows** [comment]
Thank you for quick answer, unfortunately it's the same 
```
module.first_control_plane.hcloud_server.server: Still creating... [7m30s elapsed]
module.first_control_plane.hcloud_server.server: Still creating... [7m40s elapsed]
module.first_control_plane.hcloud_server.server: Still creating... [7m50s elapsed]
module.first_control_plane.hcloud_server.server: Still creating... [8m0s elapsed]
module.first_control_plane.hcloud_server.server (remote-exec): Connecting to remote host via SSH...
module.first_control_plane.hcloud_server.server (remote-exec):   Host: ....
module.first_control_plane.hcloud_server.server (remote-exec):   User: root
module.first_control_plane.hcloud_server.server (remote-exec):   Password: false
module.first_control_plane.hcloud_server.server (remote-exec):   Private key: true
module.first_control_plane.hcloud_server.server (remote-exec):   Certificate: false
module.first_control_plane.hcloud_server.server (remote-exec):   SSH Agent: true
module.first_control_plane.hcloud_server.server (remote-exec):   Checking Host Key: false
module.first_control_plane.hcloud_server.server (remote-exec):   Target Platform: unix
module.first_control_plane.hcloud_server.server: Still creating... [8m10s elapsed]
╷
│ Error: remote-exec provisioner error
│
│   with module.first_control_plane.hcloud_server.server,
│   on modules/host/main.tf line 60, in resource "hcloud_server" "server":
│   60:   provisioner "remote-exec" {
│
│ timeout - last error: dial tcp ............:22: i/o timeout
╵
```
🤔  what is interesting whole time of terraform execution doesn't change much

**Comment by mysticaltech** [comment]
Ok, thanks, will investigate further, I'm also getting some weird behaviors lately. Keep you posted ASAP. Btw, what instance type did you use?

**Comment by mysticaltech** [comment]
@mnencia Any ideas?

**Comment by drackows** [comment]
cpx11 - all changed configuration is at the beginning of my message
I'm trying version fromn branch expose-load-balancer-ip 🤞

**Comment by mysticaltech** [comment]
If I were you, make sure to start from a fresh Hetzner project. And make sure to not touch the firewall manually?! That could be the case, or Hetzner is having problems today, as we are also experiencing weird random behaviors tonight.

**Comment by drackows** [comment]
I tried to detach server from created k3s firewall, or checked if port 22 is set as allowed and both looks good. 
ssh was possible during rescue mode (what I tried earlier)
I'll check in console what's happening during installation and I'll put screenshots here - maybe You're right about hetzners problems 🤞🏻

**Comment by phaer** [comment]
@drackows Sorry, can't answer your questions. But a few hints regarding debugging.

You could set TF_LOG=debug or even json, see https://www.terraform.io/internals/debugging . This produces a lot of log output, but can be useful if standard terraform output does not seem sufficient for debugging

But in this case, and as you mention that you can **not** reach the machine via SSH, it sounds as if networking is broken. You could try to set a user password via `ignition_config` in master.cf to set a user password and use that password to login via web console. 
When you are logged in, please check if you are able to reach remote ips (i.e. `ping 1.1.1.1`) and if not, please post the output of `ip a && ip r` to check ip addresses and the routing table

**Comment by drackows** [comment]
@phaer thanks for hints - I'll try to check with that - good idea with setting up password in ignition_config 👍🏻
I've recorded script and console - but I can not see anything from that, it looks like you wrote: something wrong must be with network
https://www.youtube.com/watch?v=U2r5fbwyMxw  at about 4:15 I've hit "Ctrl+Alt+Del" button because I wanted to show that restart server doesn't change anything, effect without this restart would be the same (video quality will be better soon after YT processing will be finished)

**Comment by mysticaltech** [comment]
Thanks for the video, it's great! 🙏

The network interfaces on Hetzner come up just fine! So that is not it.
![ksnip_20220222-015047](https://user-images.githubusercontent.com/518555/155043851-46adcc28-37b5-4355-a7e3-7a9e082dfbcc.png)

**Comment by mysticaltech** [comment]
I believe there's something up with the firewall. Just delete the whole Hetzner project, create a new one, get a new token and start over, and this time never touch any Hetzner resource manually. Because if you touch it manually, it later screws up terraform. 

Try this, and unless something on your network or machine is blocking SSH (in which case try via cloudflarewarp.com) it should work, there is no reason why not.

And you can also pull from master now, the recent PR has been merged. Good luck! :)

**Comment by drackows** [comment]
@mysticaltech last thing I've done was new project with fresh token and without success :( I tried to attach different manually created firewall with "all open" (just after terraform failed). It looks like somehow this machine is hidden from outside because locally I'm able to ssh to the machine but after incorrect login I'm getting this state:
<img width="598" alt="Screenshot 2022-02-22 at 10 29 38" src="https://user-images.githubusercontent.com/3673348/155103138-584fa97e-4ddf-4d7a-be68-bc33d9ae52f7.png">
and now locally `ssh localhost` - it looks like way to find a solution 🤞🏻

I tried what @phaer suggested too (with set password and login in console) and here is the output:
<img width="814" alt="Screenshot 2022-02-22 at 10 23 57" src="https://user-images.githubusercontent.com/3673348/155102308-a99dce3d-5095-4dd6-a576-7321d039d1a4.png">

With access to the machine I'll later try to check more things :)

**Comment by mysticaltech** [comment]
Yeah, please do. I have no idea why it would do that! Which network are you in? Try fsn1 just out of curiosity, and start fresh. Also you never need to modify the firewall manually otherwise it won't delete on destroy.

**Comment by mysticaltech** [comment]
Please pull from the latest and try again.

**Comment by drackows** [comment]
I've tried with this configuration and latest master version with the same result
```
location                  = "fsn1" # change to `ash` for us-east Ashburn, Virginia location
network_region            = "eu-central" # change to `us-east` if location is ash
agent_server_type         = "cpx21"
control_plane_server_type = "cpx11"
lb_server_type            = "lb11"

servers_num               = 3
agents_num                = 2
```

BUT I found clue (actually I found the reason why I cannot ssh to the machine and how to get round of it) 😃
I've checked iptables and there I found DROP rule with tallow list
<img width="493" alt="Screenshot 2022-02-22 at 23 50 28" src="https://user-images.githubusercontent.com/3673348/155233886-eb70e2a9-30de-4b69-ac82-0387db114b48.png">
tallow list 
<img width="799" alt="Screenshot 2022-02-22 at 23 50 36" src="https://user-images.githubusercontent.com/3673348/155234145-0bdf26ed-43d2-4177-83d0-04a52e5b8339.png">

What can help me to ssh to the machine: iptables - drop rule 😅
I couldn't find anything in terraform-s related to iptables or ipset so it needs to be somewhere in image, right?
I've checked default machine in hetzner - it has clean iptables:
<img width="334" alt="Screenshot 2022-02-22 at 23 54 27" src="https://user-images.githubusercontent.com/3673348/155234583-e8a9b0f8-440c-4e21-8cad-84044fd6c8f3.png">

What is weird now I can ssh to the machine: 
<img width="834" alt="Screenshot 2022-02-23 at 00 08 53" src="https://user-images.githubusercontent.com/3673348/155234921-7faf6bca-d782-4cde-8d18-a4bae737b367.png">
but terraform process does not continued (I've removed this rule when terraform was waiting for server to be available)
<img width="800" alt="Screenshot 2022-02-23 at 00 09 15" src="https://user-images.githubusercontent.com/3673348/155234957-11a9bda2-7fa9-4482-94b8-bbbd484220fc.png">

I'll give update here if I'll find something

**Comment by mysticaltech** [comment]
Tallow is the microos protection software , it bans abusive IPs.

So only one explanation to you problem. You ssh config in the project is not correct so you get banned by the node after a few retries.

Do you have a passphrase in you ssh private key? Please re-read the section in the readme.

Also use advanced terraform logs like TF_LOG=trace

**Comment by drackows** [comment]
omg - I forgot to check TF_LOG=trace probably there would be hint for that... and yes this was the issue of my ssh keys (I've used my existing one - which was not ed25519 🤦🏻‍♂️) - sorry for bothering you and thanks for support 🍻

It went more forward and exited during `null_resource.kustomization` - but I need to check it more deeply :)
