### ISSUE TITLE
4 node(s) had taint {node.cloudprovider.kubernetes.io/uninitialized: true}

### ISSUE THREAD

**Issue by Julian-Louis** [kube-hetzner/kube-hetzner#9]
Hello, after a fresh terraform apply at hetzner, all my pods are in ready state with the following error messages:

> 0/4 nodes are available: 4 node(s) had taint {node.cloudprovider.kubernetes.io/uninitialized: true}, that the pod didn't tolerate.

Running the commande:
`kubectl taint nodes --all node.cloudprovider.kubernetes.io/uninitialized-`
fixed the problem, but the load balancer is not created

Do, you know how can I fix it please ?

**Comment by mysticaltech** [comment]
As if the Hetzner CCM did not get installed correctly. Weird! 

Are you able to run the following command?

```
kubectl apply -k hetzer/ccm
kubectl delete -k hetzer/csi
```
 
These should run successfully, if not, your `kubectl` probably does not support customize because it's too old, see https://kustomize.io/. If that is the case just update your kubectl version!

**Comment by Julian-Louis** [comment]
Did you keep the same config than in the example config file  @dhoppe

**Comment by dhoppe** [comment]
@Julian-Louis Yes, I just changed the token and SSH Key as mentioned at the README.md.

**Comment by Julian-Louis** [comment]
@dhoppe This is strange because I did the same, I just added [this line](https://github.com/kube-hetzner/kube-hetzner/pull/8/commits/c56b6ee725d21f240104e5af3d11dd70637a1e15), but it shouldn't be the problem

**Comment by mysticaltech** [comment]
@Julian-Louis By now I understand you are on Windows, it's been a long time for me, are you using the Linux subsystem? If not, I would suggest you do, probably better than using the cmd. It may seem dumb, but I believe Terraform would behave more "vanilla" on a Linux system, hence my recommendation above.

**Comment by Julian-Louis** [comment]
I'm not using wsl but just windows

**Comment by Julian-Louis** [comment]
Using windows sub system fixed the problem, thank you a lot !
