### ISSUE TITLE
Stuck on Waiting for load-balancer to get an IP

### ISSUE THREAD

**Issue by arvin-corpuz** [kube-hetzner/kube-hetzner#93]
I am trying to create a small cluster with 1 control plane and 2 agents.  I already increased the timeout of the bash script to 500 and still having the issue. I tried to create a new project and generated a new api token and still the same.

Here's the loop output

    null_resource.first_control_plane: Still creating... [10m50s elapsed]
    null_resource.first_control_plane (remote-exec): Waiting for load-balancer to get an IP...
    null_resource.first_control_plane (remote-exec): Waiting for load-balancer to get an IP... 
    null_resource.first_control_plane (remote-exec): Waiting for load-balancer to get an IP...

Here is my vars file

    location                  = "fsn1"
    network_region            = "eu-central" 
    agent_server_type         = "cpx21"
    control_plane_server_type = "cpx11"
    lb_server_type            = "lb11"
    servers_num               = 1
    agents_num                = 2

**Comment by mysticaltech** [comment]
@arvin-corpuz Please destroy and retry. And also make sure no resources are left before. Please see how to destroy here https://github.com/kube-hetzner/kube-hetzner#takedown

Also, these last 48h Hetzner has a few issues like not connecting network interfaces or starting with the server still off, so you may have to retry a few times for it to work. Good luck!

**Comment by mysticaltech** [comment]
Please try again now @arvin-corpuz, we have identified and fixed a potential network problem in a recent push.

**Comment by arvin-corpuz** [comment]
@mysticaltech thank you for the update. pulled the update and still stuck on this part. I noticed that it does not create the load balancer (traefik.yml)

**Comment by mysticaltech** [comment]
Make sure to destroy everything before, including previous LB. It's best to use a fresh project.

**Comment by mysticaltech** [comment]
Also comment out the traefik output and the traefik data. Those are not essential, they are just to grab the LB ip. They when your cluster is up, you can investigate better if your LB still did not get an IP.

**Comment by mysticaltech** [comment]
Please try @arvin-corpuz, I would really like to get to the bottom of that issue. It cannot not work! :)

**Comment by mysticaltech** [comment]
> @mysticaltech thank you for the update. pulled the update and am still stuck on this part. I noticed that it does not create the load balancer (traefik.yml)

Basically, k3s installs Traefik, the ingress controller, which in turn requests an LB to the Hetzner CCM, which gives the IP back, and that is what we are waiting for, to display the output.

**Comment by phaer** [comment]
@arvin-corpuz If the load-balancer is not created, please check the logs of hetzner-cloud-controller-manager in your cluster.

**Comment by mysticaltech** [comment]
The code has changed significantly since that issue was opened. Please try again, and open a new issue if necessary.
