### ISSUE TITLE
Request: option to add custom certificate

### ISSUE THREAD

**Issue by michaelsstuff** [kube-hetzner/kube-hetzner#95]
The option to add an existing certificates to the hetzner loadbalaner. 
In my case I have an cloudflare origin server certificate.

**Comment by michaelsstuff** [comment]
actually nevermind. I think that is better served with a proper ingres deployment.

**Comment by mysticaltech** [comment]
Hey @michaelsstuff, I use Cloudflare's origin certificates myself. They work wonderfully with Traefik too, here's a tutorial I previously made to use them https://github.com/kube-hetzner/kube-hetzner/issues/18.

**Comment by mysticaltech** [comment]
Now if you add external-dns, it becomes magic hehe! Let me know if you haven't set it up already, will share a quick example.

**Comment by mysticaltech** [comment]
In the future, we will offer this project a terraform module, but we're not there yet. Hopefully soon.

However, it would be good to support Cloudflare optionally, as we already do that for let's encrypt, just clone, do your changes, and send us a PR. 

Terraform.tfvars is excluded from git anyway, so your private info will not be shared, and you will have to declare those variables in variables.tf also for it to work.

**Comment by mysticaltech** [comment]
I guess, in your PR, the best way would be to add your `cloudflare.tf` in the `examples` directory. Because it's a specific use case.

**Comment by phaer** [comment]
@michaelsstuff Only saw this just now. But while not "officially supported" yet, it already *is* possible to use this project as a terraform module. Just clone it and use it as normal

```
module "kube-hetzner" {
  source = "./kube-hetzner"

  # Same as terraform.tfvars.example
  hcloud_token = var.hcloud_token
  # [...]
}
```

I've been using this approach for a few weeks already to add additional resources like cloudflare_records
